Implemented nextclade version check for IRMA

diff --git a/buisciii/templates/IRMA/ANALYSIS/ANALYSIS01_IRMA/05-nextclade/lablog b/buisciii/templates/IRMA/ANALYSIS/ANALYSIS01_IRMA/05-nextclade/lablog
--- a/buisciii/templates/IRMA/ANALYSIS/ANALYSIS01_IRMA/05-nextclade/lablog
+++ b/buisciii/templates/IRMA/ANALYSIS/ANALYSIS01_IRMA/05-nextclade/lablog
@@ -11,6 +11,60 @@ if test -d B; then rm -rf B; fi
 # Auxiliary file in which a nextclade dataset is associated with a specific flu subtype.
 AUX_FILE="equivalences.txt"
 
+# Log file for nextclade version check
+logfile=$(echo "$PWD/nextclade.log")
+timestamp=$(date +"%Y-%m-%d_%H-%M-%S")
+log_message() {
+    local message="$1"
+    case "$2" in
+        "bold")
+            echo -e "\e[1;37m$message\e[0m"
+            echo -e "$timestamp - \e[1;37m$message\e[0m" >> $logfile
+            ;;
+        "red")
+            echo -e "\e[31m$message\e[0m"
+            echo -e "$timestamp - \e[31m$message\e[0m" >> $logfile
+            ;;
+        "green")
+            echo -e "\e[32m$message\e[0m"
+            echo -e "$timestamp - \e[32m$message\e[0m" >> $logfile
+            ;;
+        "blk_red")
+            echo -e "\e[1;5;97;5;41m$message\e[0m"
+            echo -e "$timestamp - \e[1;5;97;5;41m$message\e[0m" >> $logfile
+            ;;
+        *)
+            echo -e "$message"
+            echo -e "$timestamp - $message" >> $logfile
+            ;;
+    esac
+}
+
+# Nextclade version check
+update_nextclade() {
+    echo
+    log_message "Starting NEXTCLADE check/update." bold
+    log_message "Checking Nextclade container version..."
+    url=$(curl -s "https://depot.galaxyproject.org/singularity/")
+    latest_version_nextclade=$(echo "$url" | grep -oP 'nextclade:[^"]+' | sort -V | tail -n 1 | awk -F'>' '{print $1}' | sed 's/<\/a//')
+    log_message "Latest version available of Nextclade:\e[1;38;5;220m $latest_version_nextclade" bold
+
+    log_message "Checking if latest version of Nextclade image is already downloaded..."
+    if [ -e "/data/ucct/bi/pipelines/singularity-images/$latest_version_nextclade" ]; then
+        log_message "File $latest_version_nextclade already downloaded."
+        log_message "Nextclade container is UP TO DATE. \xE2\x9C\x85"
+    else
+        log_message "Downloading $latest_version_nextclade file..."
+        wget -P "/data/ucct/bi/pipelines/singularity-images" "https://depot.galaxyproject.org/singularity/$latest_version_nextclade"
+        if [ $? -eq 0 ]; then
+            log_message "$latest_version_nextclade file succesfully downloaded." green
+        else
+            log_message "An error occurred during file downloading." blk_red
+        fi
+    fi
+}
+update_nextclade
+
 echo "
   while read -r nextclade_dataset subtype_folder; do
       folder_path=\"../04-irma/\$subtype_folder\"
@@ -31,7 +85,7 @@ echo "
 
           # Run nextclade for all sequences from A_HA.txt or B_HA.txt, in order to determine their clade.
           echo \"Running nextclade for \$subtype_folder with file \$input_file...\"
-          srun --chdir ${scratch_dir} --output logs/NEXTCLADE_RUN_\${subtype_folder}_%j.log --job-name NEXTCLADE_RUN_\${subtype_folder} --partition short_idx --time 2:00:00 singularity exec -B ${scratch_dir}/../../../ /data/ucct/bi/pipelines/singularity-images/nextclade\:3.21.2--h9ee0642_0 nextclade run \"\$input_file\" -d \"\$nextclade_dataset\" -O \"./\$subtype_folder/\" --verbosity info &
+          srun --chdir ${scratch_dir} --output logs/NEXTCLADE_RUN_\${subtype_folder}_%j.log --job-name NEXTCLADE_RUN_\${subtype_folder} --partition short_idx --time 2:00:00 singularity exec -B ${scratch_dir}/../../../ /data/ucct/bi/pipelines/singularity-images/${latest_version_nextclade} nextclade run \"\$input_file\" -d \"\$nextclade_dataset\" -O \"./\$subtype_folder/\" --verbosity info &
       else
           echo \"Warning: Folder \$folder_path does not exist, skipping...\"
       fi
@@ -47,3 +101,4 @@ echo "
   python3 merge_results.py
 " > _02_run_merge_results.sh
 
+log_message "Execution completed! Now run the corresponding bash scripts" green
